### ISSUE TITLE
GelfHandler produces Fatal error when called in Garbage Collection 

### ISSUE THREAD

**Issue by SchulteMarkus** [Seldaek/monolog#614] opened 2015-07-21 10:26 UTC
In my usecase, Monolog with a GelfHandler is used in a __destruct()-function. Some pseudo-code is attached. 

When doing so, I am getting:
```
PHP Fatal error:  Call to a member function publish() on a non-object in /vagrant/vendor/monolog/monolog/src/Monolog/Handler/GelfHandler.php on line 62
PHP Stack trace:
...
PHP   4. SomeClass->__destruct() SomeClass.php:0
PHP   5. Monolog\Logger->warn() SomeClass.php:<line-nr, where ->warn() is called>
PHP   6. Monolog\Logger->addRecord() /vagrant/vendor/monolog/monolog/src/Monolog/Logger.php:503
PHP   7. Monolog\Handler\AbstractProcessingHandler->handle() /vagrant/vendor/monolog/monolog/src/Monolog/Logger.php:269
PHP   8. Monolog\Handler\GelfHandler->write() /vagrant/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:37

```

Please fix this issue.

Using monolog/monolog 1.15

```php
class SomeClass
{
    public function __destruct() 
    {
        $logger = new Logger('some name');
        $gelfPublisher = new Publisher();
        $gelfHandler = new GelfHandler($gelfPublisher);
        $logger->pushHandler($gelfHandler);

        $logger->warn('log to elk');
    }
} 
```

**Comment by Seldaek** [comment] 2015-07-31 13:32
I don't really see how that error is possible with the code you show, is this really how you're using monolog?

**Comment by Seldaek** [comment] 2015-08-09 17:24
Without more info I can not do anything about this, closing but if you want to provide more then I will reopen.

**Closed by Seldaek** 2015-08-09 17:24 UTC

**Comment by derula** [comment] 2017-06-27 17:48
I know this is two years old, but I'm actually having this problem as well.

The gist is that in the destructor of Monolog\Handler\Handler, as well as in Monolog\ErrorHandler::handleFatalError(), ->close() is called on the handler. In case of GelfHandler, it unsets the publisher, leaving itself in a broken state.

If then some other code tries to log something, be it from a destructor that is randomly executed at a later time, or, in case of handleFatalError(), in another shutdown function, instead of gracefully refusing to log anything, the GelfHandler causes (_another_) fatal.

I agree that logging from shutdown functions or constructors may not be a good idea. However, I don't think the handler should cause a fatal error in these cases. For example, StreamHandler even re-opens the stream automatically in write() if it's been closed before. (I don't know whether that's a good _idea_, but that's what happens.)

Here is a short test script to show what I'm talking about:

    <?php
    require 'vendor/autoload.php';
    $handler = new Monolog\Handler\GelfHandler(
        new Gelf\Publisher(new Gelf\Transport\UdpTransport())
    );
    $logger = new Monolog\Logger(null, [$handler]);
    Monolog\ErrorHandler::register($logger);
    register_shutdown_function(function() use ($logger) {
        $logger->debug('Something that shouldn\'t crash the application');
    });
    trigger_error('Something fatal', E_USER_ERROR);

Executing this will raise _two_ fatal errors, first "something fatal," and then "Call to a member function publish() on null." For comparison, if you don't pass the handler to the Logger constructor, effectively creating a StreamHandler, only one fatal occurs (and afterwards the debug message is logged).

This can't be intended behavior...?
