### ISSUE TITLE
Error Elasticsearch client reference and not supported _type tag

### ISSUE THREAD

**Issue by davidfabbretti** [Seldaek/monolog#1660] opened 2022-04-26 16:12 UTC
https://github.com/Seldaek/monolog/blob/4192345e260f1d51b365536199744b987e160edc/src/Monolog/Handler/ElasticsearchHandler.php#L21

Must be:

use Elastic\Elasticsearch\Client;

AND

https://github.com/Seldaek/monolog/blob/4192345e260f1d51b365536199744b987e160edc/src/Monolog/Handler/ElasticsearchHandler.php#L138

Unsupported _type tag

**Comment by davidfabbretti** [comment] 2022-04-26 16:58
400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}

**Comment by Seldaek** [comment] 2022-05-03 18:52
The problem is you're using elasticsearch/elasticsearch v8 which changed some things.

See #1662 for ES8 support, but in the meantime I suggest you use v7.

**Comment by ezimuel** [comment] 2022-05-07 14:41
@davidfabbretti the `_type` is not supported anymore in Elasticsearch 8. This parameter has been deprecated in Elasticsearch 7, read [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html) for more details.

**Comment by Seldaek** [comment] 2022-05-08 20:27
OK should be fixed by #1662

**Closed by Seldaek** 2022-05-08 20:27 UTC
Labels: Feature
