### ISSUE TITLE
Uncaught Error: Cannot instantiate interface Monolog\LogRecord

### ISSUE THREAD

**Issue by julienchey** [Seldaek/monolog#1765] opened 2022-10-03 10:09 UTC
Monolog version 3

Hello, we can't have a working installation of Monolog 3.
The logger works great for a time (about 30 min), but this error appear next, and we can't understand what's going on...
Can you help us please?

`Uncaught Error: Cannot instantiate interface Monolog\LogRecord in /var/www/ateliertuffery/httpdocs/vendor/monolog/monolog/src/Monolog/Logger.php:333 Stack trace: #0 /var/www/ateliertuffery/httpdocs/vendor/monolog/monolog/src/Monolog/Logger.php(601): Monolog\Logger->addRecord() #1
`

**Comment by stof** [comment] 2022-10-03 10:57
this looks like a bug in PHP where it messes up some cache (`Monolog\LogRecord` is not an interface at all). We heard about a similar issue in the Symfony issue tracker a few days/weeks ago.

**Comment by julienchey** [comment] 2022-10-05 10:13
> this looks like a bug in PHP where it messes up some cache (`Monolog\LogRecord` is not an interface at all). We heard about a similar issue in the Symfony issue tracker a few days/weeks ago.

@stof Do you have a link of it?


I add that if we restart PHP process, Monolog works again (then crashes again 30min/1h later).

**Comment by stof** [comment] 2022-10-05 10:16
See https://github.com/symfony/symfony/issues/47653 for the report in the Symfony issue tracker.

**Comment by PhilETaylor** [comment] 2022-10-05 12:19
Is this PHP 8? 8.2RC?

**Comment by julienchey** [comment] 2022-10-05 12:21
> Is this PHP 8? 8.2RC?

@PhilETaylor 8.1.0 :)

**Comment by PhilETaylor** [comment] 2022-10-05 13:16
Bug logged at php-src https://github.com/php/php-src/issues/9675

**Comment by PhilETaylor** [comment] 2022-11-13 12:51
For me, in PHP 8.2, This seems resolved in PHP 8.2 RC 6 released this week so "maybe" connected to something contained in https://news-web.php.net/php.internals/118991

**Comment by Seldaek** [comment] 2023-02-04 20:47
Closing as I'm assuming this is due to a PHP bug, @julienchey please reopen if it is still happening with an up to date PHP.

**Closed by Seldaek** 2023-02-04 20:47 UTC
Labels: Bug

**Comment by YazidKHALDI** [comment] 2024-09-02 14:53
I've encountered an issue with Monolog when using it in a WordPress environment with multiple plugins. The problem seems to arise due to a conflict between different versions of Monolog loaded by different plugins.

“I am developing a WordPress plugin (`my-plugin`) that uses Monolog version `3.7.0`. Meanwhile, another plugin installed in the same WordPress environment ([Google Listings and Ads for WooCommerce](https://wordpress.org/plugins/google-listings-and-ads/)) is using an older version of Monolog (`2.9.0`). This version mismatch is causing a critical conflict when trying to log records.”

```
Fatal error: Uncaught Error: Cannot instantiate interface Monolog\LogRecord in /var/www/html/wp-content/plugins/my-plugin/vendor/monolog/monolog/src/Monolog/Logger.php:358
Stack trace:
#0 /var/www/html/wp-content/plugins/my-plugin/vendor/monolog/monolog/src/Monolog/Logger.php(619): Monolog\Logger->addRecord(Object(Monolog\Level), 'ECBAbstractApi....', Array)
#1 /var/www/html/wp-content/plugins/my-plugin/libs/api/ECBAbstractApi.php(75): Monolog\Logger->notice('ECBAbstractApi....')
#2 /var/www/html/wp-content/plugins/my-plugin/libs/api/ECBAuth.php(116): ecb\libs\api\ECBAbstractApi->__construct(Array)
#3 /var/www/html/wp-content/plugins/my-plugin/functions.php(46): ecb\libs\api\ECBAuth->__construct()
#4 /var/www/html/wp-includes/class-wp-hook.php(324): upsert_ecb_user('')
#5 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /var/www/html/wp-includes/pluggable.php(48): do_action('set_current_use...')
#8 /var/www/html/wp-includes/user.php(3674): wp_set_current_user(1)
#9 /var/www/html/wp-includes/pluggable.php(70): _wp_get_current_user()
#10 /var/www/html/wp-includes/user.php(658): wp_get_current_user()
#11 /var/www/html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-manager.php(731): get_current_user_id()
#12 /var/www/html/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-tracking.php(234): Automattic\Jetpack\Connection\Manager->is_user_connected()
#13 /var/www/html/wp-content/plugins/jetpack/class.jetpack.php(953): Automattic\Jetpack\Tracking->should_enable_tracking(Object(Automattic\Jetpack\Terms_Of_Service), Object(Automattic\Jetpack\Status))
#14 /var/www/html/wp-includes/class-wp-hook.php(324): Jetpack->configure('')
#15 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#16 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#17 /var/www/html/wp-settings.php(555): do_action('plugins_loaded')
#18 /var/www/html/wp-config.php(133): require_once('/var/www/html/w...')
#19 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#20 /var/www/html/wp-admin/admin.php(34): require_once('/var/www/html/w...')
#21 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...')
#22 {main}
  thrown in /var/www/html/wp-content/plugins/my-plugin/vendor/monolog/monolog/src/Monolog/Logger.php on line 358
``` 

### Directory Structure:
Here's a simplified structure of the relevant parts of the plugins directory:

```
my-plugin
├── composer.json
├── composer.lock
├── vendor
│   │   └── monolog //3.7.0
│   │       └── src
│   │           └── Monolog
│   │               ├── Attribute
│   │               ├── Formatter
│   │               ├── Handler
│   │               ├── Processor
│   │               ├── Logger.php  // class LogRecord implements ArrayAccess
│   │               ├── LogRecord.php
│   │               └── Test

google-listings-and-ads //Google for WooCommerce
├── composer.json
├── composer.lock
├── google-listings-and-ads.php
├── vendor
│   ├── composer
│   ├── monolog //2.9.3
│   │   └── monolog
│   │       └── src
│   │           └── Monolog
│   │               ├── Attribute
│   │               ├── Formatter
│   │               ├── Handler
│   │               ├── Processor
│   │               ├── Logger.php
│   │               ├── LogRecord.php // interface LogRecord extends \ArrayAccess
│   │               └── Test
``` 

### The Core of the Issue
In Monolog 3.7.0, LogRecord is a class:

```php
// my-plugin => Monolog v3.7.0
class LogRecord implements ArrayAccess
{
    // Class implementation
}
``` 

In Monolog 2.9.0, LogRecord is an interface:

```php
// Google Listings and Ads => Monolog v2.9.0
interface LogRecord extends ArrayAccess
{
    // Interface methods
}
``` 
“When my plugin attempts to log a message, Monolog tries to instantiate the `LogRecord` class:”


```php
 $record = new LogRecord(
                datetime: $datetime ?? new DateTimeImmutable($this->microsecondTimestamps, $this->timezone),
                channel: $this->name,
                level: self::toMonologLevel($level),
                message: $message,
                context: $context,
                extra: [],
            );
``` 

“However, due to the conflict, it's trying to instantiate the `LogRecord` from the `Google Listings and Ads` plugin (which is an interface), rather than from my plugin’s version of Monolog, leading to a fatal error.”

### Possible Cause
The root cause seems to be that WordPress loads multiple plugins, each with its own dependencies, leading to conflicting class/interface definitions across different versions of Monolog. Since both versions of Monolog define LogRecord but with different types (class vs. interface), it leads to unexpected behavior.

### Environment:

PHP Version: 8.2.23
WordPress Version: 6.6.1
Monolog Version: 3.7.0 (in my-plugin)
Monolog Version: 2.9.0 (in Google Listings and Ads)

**Comment by Seldaek** [comment] 2024-09-02 14:57
@YazidKHALDI maybe you can manually do this to force it to include the monolog 3 version, which may fix it, or may break somewhere else I'm not entirely sure..

```
if (!class_exists('Monolog\LogRecord', false)) {
    include __DIR__ . '/../../path/to/vendor/monolog/monolog/src/Monolog/LogRecord.php';
}
```

There is no real solution though to this problem, PHP is not made to include two different versions of a library at once.. Unfortunately if the above doesn't work I am not sure what you can do here.
