### ISSUE TITLE
LineFormatter::formatException gives Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by pvanoudheusden** [Seldaek/monolog#1456] opened 2020-04-21 12:22 UTC
I'm getting errors on line 183/184. in LineFormatter.php 
(Object of class stdClass could not be converted to string)
If $e->detail is an object then youre using reset()? 
Removing the 's_object($e->detail)' works but what to do with objects?

**Comment by Seldaek** [comment] 2020-05-11 19:51
Duplicate of #1431

**Closed by Seldaek** 2020-05-11 19:51 UTC
Labels: Bug
