### ISSUE TITLE
Error: Typed property Monolog\DateTimeImmutable::$useMicroseconds must not be accessed before initialization

### ISSUE THREAD

**Issue by BusterNeece** [Seldaek/monolog#1786] opened 2023-01-11 23:24 UTC
Using Monolog 3.2.0 with PHP 8.2.

Attempting to provide an API response with JSON values that are serialized from the output of a `TestLogger`.

Error occurs in `DateTimeImmutable.php` and the full text is:

```
Error thrown with message "Typed property Monolog\DateTimeImmutable::$useMicroseconds must not be accessed before initialization"

Stacktrace:
#49 Error in /vendor/monolog/monolog/src/Monolog/DateTimeImmutable.php:35
#48 Monolog\DateTimeImmutable:jsonSerialize in [internal]:0
#47 json_encode in Response.php:205
```

**Comment by Seldaek** [comment] 2023-02-04 21:33
I don't understand how this is possible. How was the instance created? As you can see in https://github.com/Seldaek/monolog/blob/main/src/Monolog/DateTimeImmutable.php#L28 it does initialize the property in the constructor so unless it is created by bypassing the constructor somehow I don't see how this happens. And I don't think monolog does this so I wonder if maybe you have smth in your app that's interacting poorly with this class?

**Comment by BusterNeece** [comment] 2023-02-09 01:13
@Seldaek I looked into this further, and it just turns out that the debug log entries are being marshalled into and out of a cache, which is basically just serializing/unserializing them.

With the version of Monolog I'm using, you can reproduce this error just by running:

```php
<?php
$datetime = new \Monolog\DateTimeImmutable(true);

$datetimeSerial = serialize($datetime);
$datetimeNew = unserialize($datetimeSerial);

echo json_encode($datetimeNew);
```

Which yields:

```
Typed property Monolog\DateTimeImmutable::$useMicroseconds must not be accessed before initialization
```

I believe the cause of this is because the `useMicroseconds` property isn't preserved in the serialization process, and thus isn't set when the record is unserialized (which, to my understanding, doesn't use the `__construct` function), so the simple fix should be just to add that property to the serialized data.

**Comment by Seldaek** [comment] 2023-02-09 08:44
Right, looks like an easy fix then. I'm assuming the problem is that the base DateTimeImmutable has custom serialization in place so it does not include our custom property as I'd expect in a regular class. Thanks.

**Comment by derickr** [comment] 2023-02-09 12:40
No, this was a bug, which is now fixed: https://github.com/php/php-src/pull/10446

**Comment by Seldaek** [comment] 2023-02-09 12:48
Indeed, looks like only 8.2.0 - 8.2.2 are affected so I'll hold on fixing this I think, PHP 8.2.3 should resolve the issue.

**Comment by Seldaek** [comment] 2023-02-09 12:48
Forgot link https://3v4l.org/aXNdO

**Closed by Seldaek** 2023-02-09 12:48 UTC
Labels: Bug
