### ISSUE TITLE
problem with storing context message

### ISSUE THREAD

**Issue by mitalcoi** [Seldaek/monolog#580] opened 2015-06-15 10:15 UTC
I use StreamHandler for store logs. I put in context (second parameter) xml-responses, and sometimes it doesn't stored! I detect the reason: if context has a big size, handler ignore it.

**Comment by Seldaek** [comment] 2015-06-19 00:09
Not sure what you mean exactly, the stream handler [simply does a fwrite](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/StreamHandler.php#L93) which as far as I know has no limit on the amount you can write, but I am not sure how big we are talking about here.

**Comment by mitalcoi** [comment] 2015-06-19 12:22
I have done an experiment:
```php
function generateString($length = 1) {
        $gener = '123456789QqWwEeRrTtYyUuIiOoPp[[]]aAsSdDFfGgHhJjKkLl:;ZzXxCcVvBbNnMm';
        $length_need = min($length, strlen($gener));
        $result = '';
        while (strlen($result) < $length)
            $result .= substr(str_shuffle($gener), 0, $length_need);  // *
        return $result;
    }
        $monolog->debug("test 50000 symbol", ['response'=>gener(50000)]);//ok
        $monolog->debug("test 100000 symbol", ['response'=>gener(100000)]);//failed


```

**Comment by Seldaek** [comment] 2015-06-19 12:57
Can you show your complete test? Because I did a quick reproduction attempt with this, and it works fine.. outputs up to 10million chars in one log record.

```php
<?php

require 'vendor/autoload.php';

file_put_contents('test.log', '');
$monolog = new Monolog\Logger('log');
$monolog->pushHandler(new Monolog\Handler\StreamHandler('./test.log'));
$monolog->debug("test 50000 symbols", ['response'=>str_repeat('a', 50000)]);
$monolog->debug("test 100000 symbols", ['response'=>str_repeat('b', 100000)]);
$monolog->debug("test 200000 symbols", ['response'=>str_repeat('c', 200000)]);
$monolog->debug("test 500000 symbols", ['response'=>str_repeat('d', 500000)]);
$monolog->debug("test 1000000 symbols", ['response'=>str_repeat('e', 1000000)]);
$monolog->debug("test 10000000 symbols", ['response'=>str_repeat('f', 10000000)]);

foreach (file('test.log') as $num=>$line) {
    if (substr($line, -6) !== '"} []'."\n") {
        echo 'failed at line '.$num.', len:'.strlen($line).', content: '.substr($line, 0, 30).'...'.substr($line, -10);
    }
}
```

**Comment by Seldaek** [comment] 2015-07-12 12:27
Closing as I can't reproduce, but if you have more details feel free to add and I will reopen.

**Closed by Seldaek** 2015-07-12 12:27 UTC
