### ISSUE TITLE
use of `new DateTimeImmutable` without `\` prefix or `use` statement

### ISSUE THREAD

**Issue by alister** [Seldaek/monolog#1626] opened 2022-01-18 11:00 UTC
Monolog version 2

https://github.com/Seldaek/monolog/blob/main/src/Monolog/Logger.php#L310

	Attempted to load class "DateTimeImmutable" from namespace "Monolog".
	Did you forget a "use" statement for another namespace?

Also seen on [StackOverflow](https://stackoverflow.com/questions/70435769/attempted-to-load-class-datetimeimmutable-from-namespace-monolog-did-you-fo)

**Comment by stof** [comment] 2022-01-18 11:35
That class exists: https://github.com/Seldaek/monolog/blob/main/src/Monolog/DateTimeImmutable.php

**Comment by temp** [comment] 2022-02-04 12:32
Same problem here. We don't know what causes this, everything looks fine (we even debugged autoloading).
Ended up doing a manual `require_once dirname(__DIR__).'/vendor/monolog/monolog/src/Monolog/DateTimeImmutable.php';` in our index.php, which solves the problem, but obviously sucks :-D

Anyone got an idea what is going on?

**Comment by danhanly** [comment] 2022-02-04 15:00
This occurred for me today - verified all the files are there, so not sure what's causing it.

**Comment by philippe-levan** [comment] 2022-02-04 16:29
Hi,

An upgrade of PHP 8.1 resolved the issue for me. I am on debian 11 with the remi-repo (inside docker).

These are php 8.1 versions : 
Unpacking php8.1 (8.1.2-1+0~20220127.12+debian11~1.gbpe46588) over (8.1.1-1+0~20211220.11+debian11~1.gbp519568)

I didn't find any related bug in PHP changelog https://www.php.net/ChangeLog-8.php#8.1.2.

**Comment by philippe-levan** [comment] 2022-02-04 17:30
> Hi,
> 
> An upgrade of PHP 8.1 resolved the issue for me. I am on debian 11 with the remi-repo (inside docker).
> 
> These are php 8.1 versions : Unpacking php8.1 (8.1.2-1+0~20220127.12+debian11~1.gbpe46588) over (8.1.1-1+0~20211220.11+debian11~1.gbp519568)
> 
> I didn't find any related bug in PHP changelog https://www.php.net/ChangeLog-8.php#8.1.2.

It does not work in all situations... I don't understand what happens, but I'm not sure that the php version fixed the issue... (sorry for the noise).

**Comment by bopoda** [comment] 2022-02-11 15:04
I have the same issue in symfony app after upgrading to PHP 8.1 in some cases.

```
Attempted to load class "DateTimeImmutable" from namespace "Monolog".
Did you forget a "use" statement for another namespace?
```

Clearing opcache fixes the problem in my case.

That is stacktrace:

```
Symfony\Component\ErrorHandler\Error\
ClassNotFoundError
in /var/www/project/vendor/monolog/monolog/src/Monolog/Logger.php (line 309)
in /var/www/project/vendor/monolog/monolog/src/Monolog/Logger.php -> addRecord (line 494)
in /var/www/project/vendor/symfony/error-handler/ErrorHandler.php -> log (line 538)
in /var/www/project/vendor/composer/ClassLoader.php -> handleError (line 571)
in /var/www/project/vendor/composer/ClassLoader.php include (line 571)
in /var/www/project/vendor/composer/ClassLoader.php Composer\Autoload\includeFile (line 428)
in /var/www/project/vendor/symfony/error-handler/DebugClassLoader.php -> loadClass (line 353)
in /var/www/project/vendor/monolog/monolog/src/Monolog/Logger.php -> loadClass (line 309)
in /var/www/project/vendor/monolog/monolog/src/Monolog/Logger.php -> addRecord (line 507)
in /var/www/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> debug (line 319)
in /var/www/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> postProcess (line 162)
in /var/www/project/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 217)
in /var/www/project/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 110)
in /var/www/project/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 129)
in /var/www/project/vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 607)
ErrorHandler->handleException(object(ClassNotFoundError))
```

So, I deploy code to server with PHP 8.1 (change symlink)
1. send request to clear opcache (`opcache_reset()` in top of `index.php` if specific POST param is sent). 
2. send the first healtcheck http-request to app - response is **200** OK.
3. send the second healtcheck http-request to the same route to app - response is **500**. After that, all requests to any route fails with code 500 (btw nothing logged to var/log/). _[not always reproduced, sometimes everything is okay]_. That's "class not found" issue - as debug showed. But the class is definitely there.
4. If I clear opcache the second time, everything works fine and I can't reproduce any more till new deployment.

Once, It was reproduced on my local env. But I have no idea what's going on and how to find stable reproduce.

**Comment by Seldaek** [comment] 2022-02-15 05:56
This really seems like an opcache bug if you are all running 8.1, one of you should definitely report this to the php project.

**Comment by bopoda** [comment] 2022-02-23 09:50
I updated composer dependences to get rid of deprecation warnings, and seems the problem `Attempted to load class "DateTimeImmutable" from namespace "Monolog"` was gone for me. 
In general, it was `composer update` with a lot of minor changes and some major.
But anyway, it was strange: `composer why-not php 8.1 ` was happy even before this update. I don't know which change exactly did the trick.

**Comment by R4c00n** [comment] 2022-03-02 10:03
Some problem here. I opened a bug in php-src

**Comment by temp** [comment] 2022-03-02 18:07
> Some problem here. I opened a bug in php-src

Can you post a link to the bug?

**Comment by rogatty** [comment] 2022-03-03 11:43
I had the same issue in a Laravel app, after upgrading PHP 8.0.9 to 8.1.3 and laravel/framework from 8.40.0 to 8.67.0.

Adding `require_once dirname(__DIR__).'/vendor/monolog/monolog/src/Monolog/DateTimeImmutable.php';` helped but an even better fix was to remove `vendor` directory, reinstall dependencies and run `artisan optimize:clear`. One of these steps helped and I no longer experience the issue.

**Comment by cmb69** [comment] 2022-03-03 12:32
Upstream bug report: https://github.com/php/php-src/issues/8164. I think this ticket can be closed.

**Comment by gilbertsoft** [comment] 2022-03-31 09:21
I had the same issue in a Symfony app and finally reset the OPcache by restarting the PHP FPM service after the cache warmup did the trick. Just restart the service before the cache warump brought the error back after some request and therefor was not enough.

**Comment by gilbertsoft** [comment] 2022-03-31 09:32
> I had the same issue in a Symfony app and finally reset the OPcache by restarting the PHP FPM service after the cache warmup did the trick. Just restart the service before the cache warump brought the error back after some request and therefor was not enough.

Sadly my assumption of having the bug fixed was wrong, 5 minutes later a run again into the same issue :( If I restart the PHP FPM service again manually issue is gone for the moment. Guess it's a question of time until it's back again...

**Comment by Seldaek** [comment] 2022-03-31 10:32
I'd say track https://github.com/php/php-src/issues/8164 - and add infos there if you can, maybe getting some stack trace would help someone figure it out in php core, but not sure how easy that is on prod systems.

**Comment by gilbertsoft** [comment] 2022-03-31 10:40
> I'd say track [php/php-src#8164](https://github.com/php/php-src/issues/8164) - and add infos there if you can, maybe getting some stack trace would help someone figure it out in php core, but not sure how easy that is on prod systems.

Yeah thanks, already doing that and also thought about what to provide to get it fixed. But interesting so far I'm not longer able to reproduce after the third restart. Very weired issue...

**Comment by gilbertsoft** [comment] 2022-04-01 11:38
For me it works now, I'm not longer able to reproduce the issue!

**Comment by decaluwepatrick** [comment] 2022-04-02 06:31
> For me it works now, I'm not longer able to reproduce the issue!

How did you solve it ?

**Comment by gilbertsoft** [comment] 2022-04-02 11:32
> > For me it works now, I'm not longer able to reproduce the issue!
> 
> How did you solve it ?

Check my comment above https://github.com/Seldaek/monolog/issues/1626#issuecomment-1084314823.

Little adaption in the deployment and multiple FPM service restarts solved the issue for me.

**Comment by decaluwepatrick** [comment] 2022-04-05 10:18
> > > For me it works now, I'm not longer able to reproduce the issue!
> > 
> > 
> > How did you solve it ?
> 
> Check my comment above [#1626 (comment)](https://github.com/Seldaek/monolog/issues/1626#issuecomment-1084314823).
> 
> Little adaption in the deployment and multiple FPM service restarts solved the issue for me.

Yes we are going to solve this as well by disabling opcache and restarting FPM one extra time at the end of our deployment process. It looks a bit messy but we didn't find any other solution for now

**Comment by bopoda** [comment] 2022-04-10 21:10
> > > For me it works now, I'm not longer able to reproduce the issue!
> > 
> > 
> > How did you solve it ?
> 
> Check my comment above [#1626 (comment)](https://github.com/Seldaek/monolog/issues/1626#issuecomment-1084314823).
> 
> Little adaption in the deployment and multiple FPM service restarts solved the issue for me.

Have you checked if it was enough to reset opcache? When do you do multiple restart?
I faced with error 500 starting from the second request to app (the 1st one request was OK).

For me, FPM restart and OPcache reset - both helped, so I was reseting opcache, my comment was https://github.com/Seldaek/monolog/issues/1626#issuecomment-1036307838

I changed my deployment process:
1. several healthchecks instead of one before returning node to LB
2. reset opcache second time if healthcheck response code is 500 (later I removed this condition as can't reproduce any more)

**Comment by gilbertsoft** [comment] 2022-07-16 19:11
Seems to be resolved by PHP now see https://github.com/php/php-src/issues/8164. For me the error did not show up again so far, imho the issue here can be closed too @Seldaek .

**Comment by Seldaek** [comment] 2022-07-16 19:32
Great thanks for the update, closing then.

**Closed** 2022-07-16 19:32 UTC
Labels: Bug
