### ISSUE TITLE
Issue with Logging to stdout in Laravel 10.21 using Monolog v3 EXCEPTION#Cannot log request: fwrite(): Write of 378 bytes failed with errno=32 Broken pipe

### ISSUE THREAD

**Issue by xuandung38** [Seldaek/monolog#1860] opened 2023-12-08 19:55 UTC
Monolog version 3

Hello,

I'm currently working with Laravel 10.21 and have encountered an issue when attempting to write logs to stdout using Monolog version 3. My configuration is as follows:

```php
'stdout' => [
    'driver' => 'monolog',
    'handler' => StreamHandler::class,
    'formatter' => '\Monolog\Formatter\JsonFormatter',
    'with' => [
        'stream' => 'php://stdout',
    ],
],

```

However, this setup results in an exception:

```ruby
Exception: /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php::162 -> EXCEPTION#Cannot log request: fwrite(): Write of 378 bytes failed with errno=32 Broken pipe

```

I noticed a similar issue previously reported as [#1634](https://github.com/Seldaek/monolog/issues/1634), but it seems the problem persists. Any guidance or suggestions to resolve this would be greatly appreciated.

Thank you for your support.

Best regards,

**Comment by msobkowiak-olx** [comment] 2023-12-11 12:14
It is because of this:

https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/StreamHandler.php#L118

is_resource is not enough to handle writing to a closed socket, it needs to also check if the socket is writable, as an example:
```
 $meta = stream_get_meta_data($fp);

 if(is_writable($meta['uri'])) { 
 // stream is writable
 }
 ```
 
 Or re-create $this->stream on fwrite() error here:
 https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/StreamHandler.php#L149

**Comment by ls-tyler-roach** [comment] 2023-12-14 21:03
When can we anticipate a fix to this bug?

**Comment by Seldaek** [comment] 2023-12-18 09:15
See also comments on #1634 - I'm still waiting for a way to narrow this down.

**Comment by msobkowiak-olx** [comment] 2023-12-18 16:11
@Seldaek thanks.

This is really the same class of problem like programming over the network (although the pipe is a local object, it can be closed by the OS at any time really) - closing the pipe on the "remote" side (so the side external to the library execution context) is not detectable until you try to write to the pipe. The explanation of this can be read here - there is not much we can do about it really as it is all coded in the kernel:

https://stackoverflow.com/questions/8369506/why-does-sigpipe-exist

**Comment by Seldaek** [comment] 2023-12-19 09:57
Yeah fair enough, maybe we need to check before writing or handle that failure at least and reopen the stream if possible. I am still curious why this happens now and it didn't before though.

**Comment by msobkowiak-olx** [comment] 2023-12-19 18:13
Well, possibly due to file descriptors leak, I think this is the only scenario that can happen locally.

**Comment by ls-tyler-roach** [comment] 2023-12-20 16:56
Is it possible something with the server images changed, outside of any PHP changes, that could have caused this?

**Comment by msobkowiak-olx** [comment] 2023-12-21 09:15
Very unlikely unless PHP 8 implements is_resource or write() differently. Writing to an already closed socket will always behave like that.

Other option is lower sysctl limits for file handles (so the bug has always been there but had less chance of occuring).

**Comment by Rydgel** [comment] 2024-01-24 09:32
We have the same issue in production, occured after upgrade to PHP 8.2 and Monolog 3

**Comment by TheLevti** [comment] 2024-03-06 15:11
Hello! Encountering the same issue on many of my projects as I log to stdout with json formatter.

**Comment by stevenjweirstreet** [comment] 2024-04-08 15:41
+1 Also having this issue with Laravel on PHP 8.2 currently.

**Comment by Seldaek** [comment] 2024-04-12 21:20
Just to grasp this better, as it seems nobody feels like digging into it (+1s are nice buuut they don't solve problems..). Does it happen only in long running worker processes, or also when using fpm just processing web requests?

**Comment by Rydgel** [comment] 2024-04-12 21:23
For me, it only happened in fpm web requests. Our jobs never had this issue.

**Comment by Seldaek** [comment] 2024-04-15 08:34
Ok thanks, this is odd though..

> [@Rydgel] so far it seems that file descriptors build up until reaching the limit of the kernel, preventing any new fwrite. Rebooting our servers fix the issue for a while. It seems like the stream isn't closed properly, or at least not in all cases. I've noticed that it should be done during the `__destruct()` phase of the handler, but is there some edge cases where it isn't called? (php-fpm process crash or something else)

The way PHP works, resources should be closed and file handles released at the end of a request, even if you never call `fclose()` explicitly. It just garbage collects everything, so if it started happening with PHP 8.2 I am wondering if it is some bug in PHP itself.

Per https://github.com/Seldaek/monolog/issues/1634#issuecomment-1864715807 maybe PHP 8.1 is the cause? 

I still don't really see any clear pattern here, except for everyone using Laravel.. So maybe it's something Laravel does?

Closing the handle every time seems to cause a 15-20% slowdown in log writes vs just opening it once, if you do log a lot. If you log only one line obviously it is the same, so I am not sure if this is acceptable or not. Perhaps if we ensure at least batch writes happen in one stream open the impact would be small enough.

**Comment by Seldaek** [comment] 2024-04-15 09:32
If you want to try the fix, you can require monolog/monolog `dev-fclose2 as 2.99` (2.x) or `dev-fclose3 as 3.99` (3.x). I'd be happy to get confirmation that this fixes the problem before merging as it is strictly speaking a performance-degrading patch, I don't want to do it if not worth it.

**Comment by msobkowiak-olx** [comment] 2024-04-15 09:33
Hey @Seldaek my team experiences it on custom PHP application. I can perhaps confirm that the issue started with 8.x branch however I would not necessarily assume that the resources are always "garbage-collected" - we use PHP-FPM and the worker processes will live through some requests.

**Comment by msobkowiak-olx** [comment] 2024-04-15 09:48
@Seldaek and perhaps others - can you try out this quick patch I composed ? Sadly I dont have time to test it.

https://github.com/Seldaek/monolog/pull/1884

**Comment by TheLevti** [comment] 2024-04-15 11:53
As already mentioned, only happens in fpm context, not for long running processes/cronjobs.

I will check if we can run the patch to see if it resolves the issue.

**Comment by smepti** [comment] 2024-04-15 12:03
@Seldaek you write that "except for everyone using Laravel".. We don't use laravel. We have symfony project, php version 8.1.27, monolog version 2.9.1. And this issue happening in fpm requests.

**Comment by Seldaek** [comment] 2024-04-15 12:23
Ok then Laravel is excluded too. I really don't know what is causing it except for having too many parallel requests/workers doing stuff perhaps and reaching system file handle limits. Anyway hopefully my patch does help.

**Comment by smepti** [comment] 2024-04-15 13:35
> Ok then Laravel is excluded too. I really don't know what is causing it except for having too many parallel requests/workers doing stuff perhaps and reaching system file handle limits. Anyway hopefully my patch does help.

Our application is running in docker. It seems that there is no limit on the number of files in docker (**systemctl show docker | grep LimitNOFILE=** output LimitNOFILE=infinity). Also pm.max_children setted to 15, so unrealistic that we can hit hard limit of open files. If only someone could make a demo stand with load testing on a clean application to try to reproduce this issue. And may be edit pm.max_requests to 1 to make sure that the case is in php-fpm.
If no one will take it, then I can do it, but later

**Comment by TheLevti** [comment] 2024-04-16 15:14
`composer require monolog/monolog:"dev-fclose3"`

gives me, any quick idea how to resolve it?

```
  Problem 1
    - Root composer.json requires monolog/monolog dev-fclose3, found monolog/monolog[dev-fclose3] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - launchdarkly/launchdarkly-php is locked to version 4.3.0 and an update of this package was not requested.
    - launchdarkly/launchdarkly-php 4.3.0 requires monolog/monolog ^1.6|^2.0|^3.0 -> found monolog/monolog[dev-main, 1.6.0, ..., 1.x-dev, 2.0.0-beta1, ..., 2.x-dev, 3.0.0-RC1, ..., 3.x-dev (alias of dev-main)] but it conflicts with your root composer.json require (dev-fclose3).
  Problem 3
    - illuminate/log v10.48.8 requires monolog/monolog ^3.0 -> found monolog/monolog[dev-main, 3.0.0-RC1, ..., 3.x-dev (alias of dev-main)] but it conflicts with your root composer.json require (dev-fclose3).
    - laravel/lumen-framework v10.0.3 requires illuminate/log ^10.0 -> satisfiable by illuminate/log[v10.48.8].
    - laravel/lumen-framework is locked to version v10.0.3 and an update of this package was not requested.
```

I guess composer.json should have an entry in:

```json
"extra": {
    "branch-alias": {
        "dev-main": "3.x-dev"
    }
},
```

**Comment by Seldaek** [comment] 2024-04-16 19:13
@TheLevti that's why I said to put `"dev-fclose3 as 3.99"` as require so that composer aliases it and it passes the `^3.0` requires other packages may have on it.

**Comment by TheLevti** [comment] 2024-04-17 10:59
Worked, running it now on our test system. This might take some time to validate. So I guess in a few days I will let you know if the issue still occurs.

Would be nice if someone else can do the same.

**Comment by Seldaek** [comment] 2024-04-17 11:34
Great, thanks for trying, I'll merge and release in a couple weeks maybe once we have some real world feedback :)

**Comment by TheLevti** [comment] 2024-04-19 11:27
Instead of closing the file after each log, could we do that on shutdown? Like registering a shutdown function or so to close the resources.

**Comment by Seldaek** [comment] 2024-04-19 11:37
But that is done already in `close()`, yet it doesn't seem to work..

**Comment by HaizeW** [comment] 2024-04-30 14:40
Hello
We've been running into the same problem in our testing and develop environments
We use `Monolog 2.9.2` on `Magento 2.4.6` and `PHP 8.1`
We encountered the problem when trying to write the logs to both `stdout` and `stderr`
Unfortunately the [fclose2 patch](https://github.com/Seldaek/monolog/commit/e1b52556e771995e45f51a4dac6c4c3160525b64) didn't help much
The only thing I found that fixed the problem is this :
```
protected function streamWrite($stream, array $record): void
{
    try {
        fwrite($stream, (string) $record['formatted']);
    } catch(\Exception $e) {
        fdatasync($stream);
        fwrite($stream, (string) $record['formatted']);
    }
}
```
For some reason executing `fdatasync` before retrying `fwrite` fixed the problem
Note that `fsync` also did the job
I don't really know why this fixed the problem or if this is the cleanest way to do it but hopefully it will help you patch the module

**Comment by TheLevti** [comment] 2024-04-30 15:40
If the patch does not help, then we should not go forward with it as its definitely a performance hit to constantly open/close the file.

**Comment by Seldaek** [comment] 2024-06-28 09:36
Any news here? I have one person on https://github.com/Seldaek/monolog/pull/1883 reporting it helped, but @HaizeW here saying it did not help..

@TheLevti any feedback from prod by now?

**Comment by TheLevti** [comment] 2024-06-28 10:46
Hello, unfortunately I can not reproduce it anymore since we attempted a different approach. Our team did some adjustments on the FPM config and since then we have not seen that problem. Unfortunately this happened before I applied your fix.

**Comment by TheLevti** [comment] 2024-06-28 11:05
I also think so. In addition the additional overhead of constantly opening/closing the file is not justified here and concerning. There could be some error handling/restore attempt like @HaizeW suggested, but the proposed patch is more like a workaround that might cause other problems in my opinion.

I will get back to you with what our team changed in the fpm config.

**Comment by milosb793** [comment] 2024-07-17 12:12
Hey @TheLevti, just a sincere remainder about this, if you're able to share the changes, would mean a lot.

**Comment by Seldaek** [comment] 2024-11-11 19:17
Fixed by https://github.com/Seldaek/monolog/pull/1882 hopefully, would be happy if those who tried the previous fix would confirm if this still works for them (ping @ChipZ91).

**Closed by Seldaek** 2024-11-11 19:17 UTC
Labels: Bug

**Comment by msobkowiak-olx** [comment] 2024-12-09 09:22
@Seldaek suggestion to simplify the failure detection with:

```
    protected function streamWrite($stream, array $record): int|false
    {
        return fwrite($stream, (string) $record['formatted']);
    }
 
```
Then you can easily just check the failure with following code:
 
```
    if ($this->streamWrite($stream, $record) === false) {
    //close and write again
    } 
```
as according to the PHP Doc https://www.php.net/manual/en/function.fwrite.php

```
fwrite() raises [E_WARNING](https://www.php.net/manual/en/errorfunc.constants.php#constant.e-warning) on failure.
```

**Comment by Seldaek** [comment] 2024-12-09 10:39
I want to capture the error to convert it to an exception anyway so this wouldn't really simplify much.

**Comment by incrementaltool453** [comment] 2025-02-04 03:54
> Yeah fair enough, maybe we need to check before writing or handle that failure at least and reopen the stream if possible. I am still curious why this happens now and it didn't before though.





https://lnkr.fun/2c68057

**Comment by yufio** [comment] 2025-02-04 10:31
Just to chip in here. We have managed to solve the issue for ourselves. We have changed fpm config a bit.

In our case after updating PHP from 8.1 to 8.3 + Laravel10 -> Laravel11 (including all the version changes in dependencies like Monolog) we had issues with:
- high CPU usage (100%)
- as well as many `[fwrite(): Write of N bytes failed with errno=32 Broken pipe`

We have noticed that our servers also spin out many short lived processes and the internet search lead us to this link https://stackoverflow.com/questions/31469119/php-fpm-with-nginx-config-too-many-process
Our config did have `pm.max_requests = 500` after commenting it out (basically defaulting to 0) we have no more issues.

I hope this helps somebody.

**Comment by fredericgboutin-yapla** [comment] 2025-04-14 20:29
I'm sorry to bump an old thread but I think that `errno=32` is a very generic kind of error that can happen for so many different reasons and most of them are not related to Monolog itself (in terms of mitigation).

One thing I noticed and it is not reported anywhere in the related issues as well is that, as a **workaround**, you can always assign a custom exception handler to Monolog with `setExceptionHandler()`.

By default, there are none and Monolog simply `throw` the handler exception right away, which could be damaging - see https://github.com/Seldaek/monolog/blob/2e97231b969e0ffdeff03329b808945b4ba55e38/src/Monolog/Logger.php#L714

I don't want my production to crash because one of the Monolog handlers crashed so setting a custom handler will exactly prevent this.

Sure, it might be that the underlying problem will simply manifest later down the road but it will not involve Monolog anymore.

Here is what we did so we get "notified" on the `stderr` and through Sentry, 

```php
$monolog->setExceptionHandler(
	function (Throwable $e, array $record) {
		fwrite(STDERR, sprintf("\033[31mError in Monolog handler - %s\033[0m\n", (string)$e));

		\Sentry\SentrySdk::getCurrentHub()->withScope(
			function (\Sentry\State\Scope $scope) use ($record, $e) {
				$scope->setExtra('monolog.context', $record);
				$scope->setExtra('monolog.channel', 'Monolog');
				\Sentry\captureException($e);
			}
		);
	}
);
```

Or it can be as simple as,

```php
$monolog->setExceptionHandler(fn () => false);
```

Hope it helps,
